# ci-cd.yml (Frontend)
name: Frontend CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
jobs:
  frontend-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out code from the repository

    - name: Set up Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install frontend dependencies
      run: |
        npm ci

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.3.0  # Set up Docker Buildx for multi-platform builds

    - name: Login to DockerHub
      uses: docker/login-action@v1.10.0  # Log in to DockerHub to push the Docker image
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v2  # Build and push the Docker image to DockerHub
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/shredder_front:${{ github.sha }}
        platforms: linux/amd64,linux/arm64 # Build for multiple platforms (amd64 for Windows/Mac, arm64 for newer Macs)
        build-args: |
          VITE_RAPID_API_KEY=${{ secrets.VITE_RAPID_API_KEY }}
